apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
  type: NodePort  # Use NodePort or LoadBalancer  or ClusterIP if needed
